name: "Pulse CI"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ios-latest:
    name: Unit Tests (iOS 26.2, Xcode 26.2)
    runs-on: macOS-26
    timeout-minutes: 20
    env:
      DEVELOPER_DIR: /Applications/Xcode_26.2.app/Contents/Developer
    steps:
      - uses: actions/checkout@v4
      - name: Boot simulator
        run: |
          xcrun simctl boot "iPhone 17 Pro"
          xcrun simctl bootstatus "iPhone 17 Pro" -b
      - name: Run Tests
        run: |
          .scripts/build.sh -s "Pulse" -d "OS=26.2,name=iPhone 17 Pro"
          .scripts/build.sh -s "PulseUI" -d "OS=26.2,name=iPhone 17 Pro"
  macos-latest:
    name: Unit Tests (macOS, Xcode 26.2)
    runs-on: macOS-26
    timeout-minutes: 20
    env:
      DEVELOPER_DIR: /Applications/Xcode_26.2.app/Contents/Developer
    steps:
      - uses: actions/checkout@v4
      - name: Run Tests
        run: .scripts/build.sh -d "platform=macOS"
  tvos-latest:
    name: Unit Tests (tvOS 26.2, Xcode 26.2)
    runs-on: macOS-26
    timeout-minutes: 20
    env:
      DEVELOPER_DIR: /Applications/Xcode_26.2.app/Contents/Developer
    steps:
      - uses: actions/checkout@v4
      - name: Boot simulator
        run: |
          xcrun simctl boot "Apple TV"
          xcrun simctl bootstatus "Apple TV" -b
      - name: Run Tests
        run: |
          .scripts/build.sh -s "Pulse" -d "OS=26.2,name=Apple TV"
          .scripts/build.sh -s "PulseUI" -d "OS=26.2,name=Apple TV"
# There is a problem with watchOS runners where they often fail to launch on CI
#
#  watchos-latest:
#    name: Run Build (watchOS 26.2, Xcode 26.2)
#    runs-on: macOS-26
#    timeout-minutes: 20
#    env:
#      DEVELOPER_DIR: /Applications/Xcode_26.2.app/Contents/Developer
#    steps:
#      - uses: actions/checkout@v4
#      - name: Run Tests
#        run: |
#          .scripts/build.sh -s "Pulse" -d "OS=26.2,name=Apple Watch Series 10 (46mm)"
#          .scripts/build.sh -s "PulseUI" -d "OS=26.2,name=Apple Watch Series 10 (46mm)"
  macos-xcode-26-0:
    name: Unit Tests (macOS, Xcode 26.0)
    runs-on: macOS-26
    timeout-minutes: 20
    env:
      DEVELOPER_DIR: /Applications/Xcode_26.0.app/Contents/Developer
    steps:
      - uses: actions/checkout@v4
      - name: Run Tests
        run: .scripts/build.sh -d "platform=macOS"
  swift-build:
    name: Swift Build (SPM)
    runs-on: macOS-26
    timeout-minutes: 20
    env:
      DEVELOPER_DIR: /Applications/Xcode_26.2.app/Contents/Developer
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: swift build
  build-demo-ios:
    name: Build Demo (iOS)
    runs-on: macOS-26
    timeout-minutes: 20
    env:
      DEVELOPER_DIR: /Applications/Xcode_26.2.app/Contents/Developer
    steps:
      - uses: actions/checkout@v4
      - name: Boot simulator
        run: |
          xcrun simctl boot "iPhone 17 Pro"
          xcrun simctl bootstatus "iPhone 17 Pro" -b
      - name: Build Demo
        run: |
          cd Demo
          set -o pipefail
          xcodebuild build -scheme "Pulse Demo iOS" -destination "OS=26.2,name=iPhone 17 Pro" | xcpretty
  build-demo-tvos:
    name: Build Demo (tvOS)
    runs-on: macOS-26
    timeout-minutes: 20
    env:
      DEVELOPER_DIR: /Applications/Xcode_26.2.app/Contents/Developer
    steps:
      - uses: actions/checkout@v4
      - name: Boot simulator
        run: |
          xcrun simctl boot "Apple TV"
          xcrun simctl bootstatus "Apple TV" -b
      - name: Build Demo
        run: |
          cd Demo
          set -o pipefail
          xcodebuild build -scheme "Pulse Demo tvOS" -destination "OS=26.2,name=Apple TV" | xcpretty
  build-integration-examples-ios:
    name: Build Integration Examples (iOS)
    runs-on: macOS-26
    timeout-minutes: 20
    env:
      DEVELOPER_DIR: /Applications/Xcode_26.2.app/Contents/Developer
    steps:
      - uses: actions/checkout@v4
      - name: Boot simulator
        run: |
          xcrun simctl boot "iPhone 17 Pro"
          xcrun simctl bootstatus "iPhone 17 Pro" -b
      - name: Build Integration Tests
        run: |
          cd Demo
          set -o pipefail
          xcodebuild build -scheme "Pulse Integration Examples iOS" -destination "OS=26.2,name=iPhone 17 Pro" | xcpretty
